spring.application.name=feedbackapp

spring.datasource.url=jdbc:mysql://localhost:3306/feedbackdb
spring.datasource.username=root
spring.datasource.password=Mouli@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.port=8080